version: 2

jobs:
  install-blog-dependencies:
    shell: /bin/bash
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: /tmp/blog
      - checkout
      - run: sudo apt-get install tree
      - run: tree
      - run: bash ./scripts/blog/install.sh
      - run: ls
      - persist_to_workspace:
          root: /tmp/blog
          paths: packages/blog
  build-blog:
    shell: /bin/bash
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: /tmp/blog
      - run: echo $PWD
      - run: ls
      - run: bash ./scripts/blog/build.sh
      - persist_to_workspace:
          root: .
          paths: packages/blog/public/**/*
  deploy-blog:
    shell: /bin/bash
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: /tmp/blog
      - checkout
      - run: npm install
      - run: npm run ts-node ./scripts/blog/deploy.ts

workflows:
  version: 2
  build-and-deploy-blog:
    jobs:
      - install-blog-dependencies
      - build-blog:
          requires:
            - install-blog-dependencies
      - deploy-blog:
          requires:
            - install-blog-dependencies
            - build-blog
