version: 2

# BLOG_WORKING_DIRECTORY: &blog_working_directory /tmp/workspace/log

jobs:
  install-blog-dependencies:
    shell: /bin/bash
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: bash ./scripts/blog/install.sh
      - persist_to_workspace:
          root: .
          paths: .
  build-blog:
    shell: /bin/bash
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: .
      - run: sudo apt-get install tree
      - run: tree
      - run: echo $PWD
      - run: ls
      - run: bash ./scripts/blog/build.sh
      - persist_to_workspace:
          root: .
          paths: .
  deploy-blog:
    shell: /bin/bash
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: npm install
      - run: npm run ts-node ./scripts/blog/deploy.ts

workflows:
  version: 2
  build-and-deploy-blog:
    jobs:
      - install-blog-dependencies
      - build-blog:
          requires:
            - install-blog-dependencies
      - deploy-blog:
          requires:
            - install-blog-dependencies
            - build-blog
