version: 2

jobs:
  install-blog-dependencies:
    shell: /bin/bash
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: bash ./scripts/blog/install.sh
      - persist_to_workspace:
          root: .
          paths: .
  build-blog:
    shell: /bin/bash
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: .
      - run: bash ./scripts/blog/build.sh
      - persist_to_workspace:
          root: .
          paths: packages/blog/public
  deploy-blog:
    shell: /bin/bash
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: .
      - run:
          name: deploy to blog repo
          command: |
            cd packages/blog/public
            git init
            git remote add origin https://github.com/hrg921/blog.git
            git checkout -b gh-pages
            git config credential.helper 'cache --timeout=120'
            git config user.email "hrg921@gmail.com"
            git config user.name "Circle CI, GeonHo Tony Han"
            git add .
            git commit -m "Deploy via CircleCI"
            # Push quietly to prevent showing the token in log
            git push -q -f https://${GITHUB_PERSONAL_TOKEN}@github.com/hrg921/blog.git

workflows:
  version: 2
  build-and-deploy-blog:
    jobs:
      - install-blog-dependencies
      - build-blog:
          requires:
            - install-blog-dependencies
      - deploy-blog:
          requires:
            - install-blog-dependencies
            - build-blog
