service:
  name: financial
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  create-account:
    handler: src/handlers/AccountHandler.createAccount
    events:
      - http:
          method: post
          path: create-account
